/*
 * Copyright (C) 2018
 * Área Académica de Ingeniería en Computadoras, ITCR, Costa Rica
 *
 * This file is part of the numerical analysis lecture CE3102 at TEC
 *
 * Automatically generated by CMake using the template cmake/AnpiConfig.hpp.in
 */

#define ANPI_ENABLE_SIMD
/* #undef ANPI_ENABLE_OpenMP */
#define ANPI_DATA_PATH "/home/diego/Escritorio/Proyecto2/ANPIProject2/code/data"
